jobs:
  include:
    - language: node_js
      node_js: 12
      before_install:
      - chmod +x ./frontend
      before_script: cd frontend
      script:
      - npm install && ng build

    - language: java
      jdk:
       - oraclejdk9
      addons:
          sonarcloud:
            organization: "oxscar93"
            token:
              secure: "8d241df986865165c19aeb3c713d81b43216b794" # encrypted value of your token
      before_install:
       - chmod +x ./backend/gradlew
      before_script: cd backend
      script: ./gradlew build --continue
      script: ./gradlew sonarqube
